## MM

In [10]:
from glob import glob
from explicit_memory.utils import read_yaml
import pandas as pd
import numpy as np

results_all = []
for results_path in glob("./training_results/DQN/mm/LSTM/m/100/*/results.yaml"):
    train_path = results_path.replace("results.yaml", "train.yaml")
    train = read_yaml(train_path)
    results = read_yaml(results_path)
    results_all.append(
        {
            "#_iterations": train["num_iterations"],
            "replay_size": train["replay_buffer_size"],
            "warm": train["warm_start"],
            "gamma": train["gamma"],
            "bs": train["batch_size"],
            "target_update": train["target_update_interval"],
            "epsilon_decay": train["epsilon_decay_until"],
            "ddqn": train["ddqn"],
            "dueling": train["dueling_dqn"],
            "split_reward": train["split_reward_training"],
            "test": results["test_score"]["mean"],
            "val": max([foo["mean"] for foo in results["validation_score"]]),
            "path": results_path.split("/")[-2],
        }
    )

df = pd.DataFrame(results_all)
df_sorted = df.sort_values(by="test", ascending=False)
print(f"number of training results: {len(df_sorted)}")

top_k = 10
df_sorted[:top_k]

number of training results: 48

,#_iterations,replay_size,warm,gamma,bs,target_update,epsilon_decay,ddqn,dueling,split_reward,test,val,path
39,1000,1000,250.0,0.934490,32,10,1000.0,True,True,False,346.2,379.9,2024-03-10 16:25:56.276974
20,1000,1000,500.0,0.817373,128,10,500.0,False,False,False,343.5,376.9,2024-03-10 16:08:18.176772
2,1000,1000,250.0,0.796604,128,10,500.0,False,True,False,335.9,288.2,2024-03-10 15:13:39.282242
12,1000,1000,1000.0,0.777101,32,50,500.0,True,True,False,332.4,310.3,2024-03-10 16:13:08.618237
32,1000,1000,1000.0,0.998022,128,100,1000.0,True,True,False,315.2,276.9,2024-03-10 14:40:41.116976
14,1000,1000,250.0,0.700544,32,50,1000.0,True,False,False,313.0,299.1,2024-03-10 15:59:22.446151
19,1000,1000,500.0,0.838924,128,50,250.0,True,True,False,306.3,337.4,2024-03-10 15:02:32.174046
47,1000,1000,1000.0,0.953608,64,50,1000.0,True,True,False,300.0,335.9,2024-03-10 16:22:06.269658
30,1000,1000,250.0,0.797212,64,50,1000.0,False,False,False,293.8,262.2,2024-03-10 16:28:45.877706
6,1000,1000,250.0,0.738597,64,10,500.0,True,True,False,293.4,297.5,2024-03-10 14:01:42.886624

## Explore

In [ ]:
from glob import glob
from explicit_memory.utils import read_yaml
import pandas as pd
import numpy as np

results_all = []
for results_path in glob("./training_results/DQN/explore/LSTM/s/*/results.yaml"):
    train_path = results_path.replace("results.yaml", "train.yaml")
    train = read_yaml(train_path)
    results = read_yaml(results_path)
    results_all.append(
        {
            "#_iterations": train["num_iterations"],
            "replay_size": train["replay_buffer_size"],
            "warm": train["warm_start"],
            "gamma": train["gamma"],
            "bs": train["batch_size"],
            "target_update": train["target_update_interval"],
            "epsilon_decay": train["epsilon_decay_until"],
            # "ddqn": train["ddqn"],
            # "dueling": train["dueling_dqn"],
            "test": results["test_score"]["mean"],
            "val": max([foo["mean"] for foo in results["validation_score"]]),
            "path": results_path.split("/")[-2],
        }
    )

df = pd.DataFrame(results_all)
df_sorted = df.sort_values(by="test", ascending=False)
print(f"number of training results: {len(df_sorted)}")

top_k = 10
df_sorted[:top_k]

In [ ]:
df_sorted[:top_k].select_dtypes(include=[np.number, bool]).mean()